config/routes.rb
OnlineCourse::Engine.routes.draw do

  resources :topics
  resources :subjects do
    resources :topics
  end
  resources :areas do
    resources :subjects
  end

  root to: 'books#index'
end

app/models/online_course/application_record.rb
module OnlineCourse
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/online_course/area.rb
module OnlineCourse
  # Contains areas to study
  class Area < ApplicationRecord
    has_many :subjects
  end
end

app/models/online_course/chapter.rb
module OnlineCourse
  class Chapter < ApplicationRecord
  end
end

app/models/online_course/subject.rb
module OnlineCourse
  class Subject < ApplicationRecord
    belongs_to :area
    has_many :topics
  end
end

app/models/online_course/topic.rb
module OnlineCourse
  class Topic < ApplicationRecord
    belongs_to :subject
  end
end

app/controllers/online_course/application_controller.rb
# ApplicationController that inherits from Parent Applicant
class OnlineCourse::ApplicationController < ::ApplicationController
  protect_from_forgery with: :exception
end

app/controllers/online_course/areas_controller.rb
require_dependency "online_course/application_controller"

module OnlineCourse
  class AreasController < ApplicationController
    before_action :set_area, only: [:show, :edit, :update, :destroy]

    # GET /areas
    def index
      @areas = Area.all
    end

    # GET /areas/1
    def show
      @subjects = @area.subjects
    end

    # GET /areas/new
    def new
      @area = Area.new
    end

    # GET /areas/1/edit
    def edit
    end

    # POST /areas
    def create
      @area = Area.new(area_params)

      if @area.save
        redirect_to @area, notice: 'Area was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /areas/1
    def update
      if @area.update(area_params)
        redirect_to @area, notice: 'Area was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /areas/1
    def destroy
      @area.destroy
      redirect_to areas_url, notice: 'Area was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_area
        @area = Area.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def area_params
        params.require(:area).permit(:name)
      end
  end
end

app/controllers/online_course/subjects_controller.rb
require_dependency "online_course/application_controller"

module OnlineCourse
  class SubjectsController < ApplicationController
    before_action :set_subject, only: [:show, :edit, :update, :destroy]

    # GET /subjects
    def index
      @subjects = Subject.all
    end

    # GET /subjects/1
    def show
      @topics = @subject.topics
    end

    # GET /subjects/new
    def new
      @subject = Subject.new
    end

    # GET /subjects/1/edit
    def edit
    end

    # POST /subjects
    def create
      @area = Area.find(params[:area_id])
      @subject = @area.subjects.create!(subject_params)

      redirect_to @area
    end

    # PATCH/PUT /subjects/1
    def update
      if @subject.update(subject_params)
        redirect_to @subject, notice: 'Subject was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /subjects/1
    def destroy
      @subject.destroy
      redirect_to subjects_url, notice: 'Subject was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_subject
        @subject = Subject.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def subject_params
        params.require(:subject).permit(:name, :area_id)
      end
  end
end

app/controllers/online_course/topics_controller.rb
require_dependency "online_course/application_controller"

module OnlineCourse
  class TopicsController < ApplicationController
    before_action :set_topic, only: [:show, :edit, :update, :destroy]

    # GET /topics
    def index
      @topics = Topic.all
    end

    # GET /topics/1
    def show
    end

    # GET /topics/new
    def new
      @topic = Topic.new
    end

    # GET /topics/1/edit
    def edit
    end

    # POST /topics
    def create
      @subject = Subject.find(params[:subject_id])
      @topic = @subject.topics.create!(topic_params)

      redirect_to @subject
    end

    # PATCH/PUT /topics/1
    def update
      if @topic.update(topic_params)
        redirect_to @topic, notice: 'Topic was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /topics/1
    def destroy
      @topic.destroy
      redirect_to topics_url, notice: 'Topic was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_topic
        @topic = Topic.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def topic_params
        params.require(:topic).permit(:name, :subject_id, :content)
      end
  end
end

app/helpers/online_course/application_helper.rb
module OnlineCourse
  module ApplicationHelper
  end
end

app/helpers/online_course/areas_helper.rb
module OnlineCourse
  module AreasHelper
  end
end

app/helpers/online_course/chapters_helper.rb
module OnlineCourse
  module ChaptersHelper
  end
end

app/helpers/online_course/subjects_helper.rb
module OnlineCourse
  module SubjectsHelper
  end
end

app/helpers/online_course/topics_helper.rb
module OnlineCourse
  module TopicsHelper
  end
end

app/views/online_course/areas/_form.html.erb
<%= simple_form_for area do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/online_course/areas/_show.html.erb
<div id="course-content">

  <% @area.subjects.each do |subject| %>
    <p class="subject-item"><%= link_to subject.name, subject, remote: true %></p>
  <% end %>

</div>

app/views/online_course/areas/edit.html.erb
<h1>Editing Area</h1>

<%= render 'form', area: @area %>

<%= link_to 'Show', @area %> |
<%= link_to 'Back', areas_path %>

app/views/online_course/areas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Areas</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @areas.each do |area| %>
      <tr>
        <td><%= area.name %></td>
        <td><%= link_to 'Show', area %></td>
        <td><%= link_to 'Edit', edit_area_path(area) %></td>
        <td><%= link_to 'Destroy', area, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Area', new_area_path %>

app/views/online_course/areas/new.html.erb
<h1>New Area</h1>

<%= render 'form', area: @area %>

<%= link_to 'Back', areas_path %>

app/views/online_course/areas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @area.name %>
</p>

<h2>Subjects</h2>

<table class="table">
  <thead>
  <tr>
    <th>Name</th>
    <th>Area</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @subjects.each do |subject| %>
    <tr>
      <td><%= subject.name %></td>
      <td><%= subject.area.name %></td>
      <td><%= link_to 'Show', subject, class: "btn btn-outline-primary btn-sm" %></td>
      <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
      <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= render 'online_course/subjects/form' %>

<%= link_to 'Edit', edit_area_path(@area) %> |
<%= link_to 'Back', areas_path %>

app/views/online_course/areas/show.js.erb
$('#course-content').replaceWith('<%= j render 'online_course/areas/show' %>');

app/views/online_course/subjects/_form.html.erb
<%= simple_form_for [@area, @area.subjects.build] do |f| %>

  <div class="field">
    <%= f.input :name, id: :subject_name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/online_course/subjects/_show.html.erb
<div id="course-content">

  <% @subject.topics.each do |topic| %>
    <p class="topic-item"><%= link_to topic.name, topic, remote: true %></p>
  <% end %>

</div>

app/views/online_course/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= simple_form_for @subject do |f| %>

  <div class="field">
    <%= f.input :name, id: :subject_name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/online_course/subjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subjects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Area</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.name %></td>
        <td><%= subject.area %></td>
        <td><%= link_to 'Show', subject %></td>
        <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
        <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subject', new_subject_path %>

app/views/online_course/subjects/new.html.erb
<h1>New Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Back', subjects_path %>

app/views/online_course/subjects/show.html.erb
<h1><%= @subject.name %></h1>

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to @subject.area.name, @subject.area %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= @subject.name %></li>
  </ol>
</nav>

<h1>Topics</h1>

<div class="row">
  <div class="col-md-9">
    <table class="table">
      <thead>
      <tr>
        <th>Name</th>
        <th></th>
      </tr>
      </thead>

      <tbody>
      <% @topics.each do |topic| %>
        <tr>
          <td><%= topic.name %></td>
          <td class="text-right">
            <div class="btn-group btn-group-sm">
              <%= link_to 'Show', topic, class: "btn btn-outline-primary" %>
              <%= link_to 'Edit', edit_topic_path(topic), class: "btn btn-outline-primary" %>
              <%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-warning" %>
            </div>
          </td>
        </tr>
      <% end %>
      <tr>
        <td></td>
        <td><%= render 'online_course/topics/form' %></td>
      </tr>
      </tbody>
    </table>
  </div>
  <div class="col-md-3">
    <%= link_to 'Edit', edit_subject_path(@subject), class: "btn btn-outline-secondary btn-block" %>
  </div>
</div>

app/views/online_course/subjects/show.js.erb
$('#course-content').replaceWith('<%= j render 'online_course/subjects/show' %>');

app/views/online_course/topics/_form.html.erb
<button type="button" class="btn btn-outline-primary btn-sm btn-block" data-toggle="modal" data-target="#addTopic">
  At Topic
</button>

<!-- Modal -->
<%= simple_form_for [@subject, @subject.topics.build] do |f| %>
  <div class="modal fade" id="addTopic" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= f.input :name %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.button :submit %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/online_course/topics/_topic.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to @topic.subject.area.name, @topic.subject.area, remote: true %></li>
    <li class="breadcrumb-item"><%= link_to @topic.subject.name, @topic.subject, remote: true %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= @topic.name %></li>
  </ol>
</nav>

<h1><%= @topic.name %></h1>

<div class="row justify-content-md-center">
  <div class="col-md-6">
    <%= raw @topic.content %>
  </div>
</div>

app/views/online_course/topics/edit.html.erb
<h1>Editing Topic</h1>

<div class="row justify-content-md-center">
  <div class="col-md-6">
    <%= simple_form_for @topic do |f| %>
      <%= f.input :name %>
      <%= f.input :content, as: :summernote %>
      <%= f.button :submit %>
    <% end %>
  </div>
</div>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/online_course/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Topics</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Subject</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.name %></td>
        <td><%= topic.subject %></td>
        <td>
          <%= link_to 'Show', topic %>
          <%= link_to 'Edit', edit_topic_path(topic) %>
          <%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_topic_path %>

app/views/online_course/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Back', topics_path %>

app/views/online_course/topics/show.html.erb
<h1><%= @topic.name %></h1>

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to @topic.subject.area.name, @topic.subject.area %></li>
    <li class="breadcrumb-item"><%= link_to @topic.subject.name, @topic.subject %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= @topic.name %></li>
  </ol>
</nav>

<div class="row justify-content-md-end">
  <div class="col-md-6">
    <%= raw @topic.content %>
  </div>
  <div class="col-md-3">
    <%= link_to "Edit", edit_topic_path(@topic), class: "btn btn-outline-primary btn-block" %>
  </div>
</div>

app/views/online_course/topics/show.js.erb
$('#course-content').replaceWith('<%= j render @topic %>');